version: "3"
services:
  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
    networks:
      - app-tier

  backend:
    env_file:
      - .env
    build:
      context: .
    command: gradle bootRun
    container_name: backend
    networks:
      - app-tier
    depends_on:
      - db
    restart: on-failure
    tty: true

networks:
  app-tier:
    driver: bridge