spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: 1234
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 963473435536-aatrc4e6iulcd55ro429jn15ntifio3n.apps.googleusercontent.com
            client-secret: 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
            scope: email

          kakao:
            client-id: 75be136585c3bb1b06fc39daf3b3ff22
            client-secret: jfPJK4LOXiBABysfYwbTAzJYQYYX3sux
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao (설정한 redirect URI)
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


#server:
#  servlet:
#    context-path: /api/v1
jwt:
  secretKey: asdlfsflej@asdfjI**!~~~jldasjlfjasfasdlfkjalsf

  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh
